### PR TITLE
FMS 2020.04.03 

### PR DESCRIPTION
**Pull request by mlee03**
## Description

This PR 
1. updates FMS to version `2020.04.03` which provides an updated FMS `CMakeLists.txt` file.
2. updates the UFS Weather Model top level `CMakeLists.txt` file to use the FMS `CMakeLists.txt` file.

Answer changes are not expected.  There are no library updates in this PR.  
The only difference between FMS `2020.04.03` and the currently used `2020.04.01` is the CMakeLists.txt file.  

### Issue(s) addressed
- fixes #440 

## Testing
All regression tests passed on Hera and Orion with Intel.

## Dependencies
There are no dependencies

### CODE REVIEW

**Comment by mlee03** [comment]
@pjpegion, I have access to Gaea, Hera, and Orion.  Let me know if you need an additional hand running the regression tests.

**Review by pjpegion — APPROVED** [review]

**Comment by pjpegion** [comment]
I am going to run a few tests on hera, and if all goes will, I can run on orion, but will need help on Gaea

**Comment by pjpegion** [comment]
@mlee03 There was a conflict with the CMakeLists.txt file, and It looks like I did not resolve the conflict correctly, and the model is not building.  Compile error file is on hera: /scratch2/BMC/gsienkf/Philip.Pegion/stmp2/Philip.Pegion/FV3_RT/rt_123699/compile_1/err
Can you take a look?  My merge code is in /scratch2/BMC/gsienkf/Philip.Pegion/ufs-weather-model.rt/

**Comment by mlee03** [comment]
@pjpegion, it seems like the problem is in the FV3/CMakeLists.txt 
 
When I clone your branch, [line 197 ](https://github.com/pjpegion/fv3atm/blob/a16337e5d264326814d719f0a8dc6fdf7cb55e10/CMakeLists.txt#L197) is missing  stochastic_physics in the TARGET list

I can run the regression tests on Gaea

**Comment by mlee03** [comment]
Sorry, linked the wrong line in the above comment.  Edited it to link to the correct file and line number

**Comment by pjpegion** [comment]
No problem. I also have to revert the MOM6/CMakeLists.txt.  I oringally made changes to ./CMakeLists.txt, MOM6/CmakeLists.txt, and FV3atm/CMakeLists.txt to get the ocean stochastic physics to build.  But since the ocean stochastics are part of this PR, we will cross that bridge when we get to it.

**Comment by mlee03** [comment]
@pjpegion, the [Gaea log](https://github.com/mlee03/ufs-weather-model/blob/fms/2020.04.03withStochUpdates372/tests/RegressionTests_gaea.intel.log) is in branch fms/2020.04.03withStochUpdates372:

<pre> git clone --recursive --branch fms/2020.04.03withStochUpdates372 https://github.com/mlee03/ufs-weather-model.git </pre>

Regression tests 15-18 have failed. 
Do you want me to make a PR to your branch again with the Gaea log?

**Comment by pjpegion** [comment]
@mlee03 Uh-oh. I  see those are compilations that failed, there are a bunch of tests that failed too.  
 We will need to generate new baselines for the following once we sort out the other issues.
Do you have any of the compilation errors saved?

New baselines will need to be generated for:
fv3_ccpp_stochy
fv3_ccpp_lndp
fv3_ccpp_gfs_v16_stochy

**Comment by mlee03** [comment]
@pjpegion, great news, the compile error is 

> CMake Error at MOM6-interface/CMakeLists.txt:30:
> Parse error.  Function missing ending ")".  End of file reached.

**Comment by pjpegion** [comment]
I just pushed the fix.  I will start the tests on hera on orion before creating the new baselines

**Comment by pjpegion** [comment]
@mlee03 I am still having issues with the DATM compilations.  I don't know enough about Cmake to easily fix this.  

error is: 

CMake Error: install(EXPORT "ufs-config" ...) includes target "ufs" which requires target "stochastic_physics" that is not in any export set.
CMake Warning:

**Comment by mlee03** [comment]
@pjpegion, just saw your comment.  I'll look into it :)

**Comment by pjpegion** [comment]
I think I will need to just use your CmakeLists.txt files. The modifications I made for the ocean stochastic physics are not needed at this point since the ocean model updates are not going in with this PR.

**Comment by pjpegion** [comment]
@mlee03 that didn't work.  I still need stochastic_physics at the FV3atm level since I have have calls in the cap.

**Comment by mlee03** [comment]
@pjpegion, adding stochastic_physics to the TARGETS list on [line 324](https://github.com/pjpegion/ufs-weather-model/blob/stoch_updates/CMakeLists.txt#L324l) seems to work.

But I think putting in an explicit install section in the stochastic_physics/CMakeLists.txt might be better.  I'll test it out.

**Comment by mlee03** [comment]
@pjpegion, 

1.  removing stochastic_physics from the install target list in FV3/CMakeLists.txt [here
](https://github.com/mlee03/ufs-weather-model/blob/cmake_tmp/FV3_CMakeLists.txt#L197l)

2.  and adding the install section to stochastic_physics/CMakeLists.txt [here](https://github.com/mlee03/ufs-weather-model/blob/cmake_tmp/stoch_phys_CMakeLists.txt#L64)

seems to work for all compile.

The fail_test for Gaea is [here](https://github.com/mlee03/ufs-weather-model/blob/cmake_tmp/tests/fail_test)

**Comment by pjpegion** [comment]
@mlee03 Can you point me to your test directory on gaea?  I would like to see why these tests are failing.

**Comment by mlee03** [comment]
@pjpegion, the logs are in 
cd /lustre/f2/scratch/Mikyung.Lee/stochupdates-cmakefail/tests/log_gaea.intel

**Comment by pjpegion** [comment]
@mlee03 Thanks, I will take your CMakeLists.txt changes, and will work on the rest of the RT errors.

**Pull request merged**
